order item controler included
LFortunatoC/AggregareRioApi pull request #13
Opened 2020-02-17 00:50 UTC by moysescl

2020-02-17 03:41 UTC, LFortunatoC requested changes

2020-02-17 03:41 UTC, LFortunatoC commented on app/Http/Controllers/ItemOrderController.php
> +        $itemOr = ItemOrder::paginate(10);
Why Pagination changed here to 10 instead of 15 any reason?

2020-02-17 03:41 UTC, LFortunatoC commented on app/Http/Controllers/ItemOrderController.php
> +            'id' => 'required|int',
Id here will be generated by the database, it must not be here

2020-02-17 03:41 UTC, LFortunatoC commented on app/Http/Controllers/ItemOrderController.php
> +        return response($itemOr,10);
The 200 is the status of the transaction and it means success, 10 Has no meaning. Please change it back to 200

2020-02-17 03:41 UTC, LFortunatoC commented on app/Http/Controllers/ItemOrderController.php
> +            'id' => 'required|int',
Id is already a parameter look... (Request $request, $id). No need to validate id here.

2020-02-17 03:41 UTC, LFortunatoC commented on app/Http/Controllers/ItemOrderController.php
> +       $category = ItemOrder::findOrFail($id);
Not $category here but $ItemOr, please take care with code quality

2020-02-20 01:14 UTC, moysescl commented
Working after rename table item_Orders

2020-02-22 14:07 UTC, closed without merging

2020-02-22 14:08 UTC, LFortunatoC commented
Changes not accepted errors were not fixed....