Created tables Order and ItemOrder
LFortunatoC/AggregareRioApi pull request #6
Opened 2020-02-13 21:46 UTC by joaoryff

2020-02-13 21:49 UTC, MauAFDias commented on database/migrations/2020_02_13_210224_create_item_order_table.php
> +            $table->bigIncrements('id');
Good test :)

2020-02-13 21:52 UTC, MauDevFernandes approved these changes
2 out 9 files approved

2020-02-15 02:56 UTC, LFortunatoC commented on database/migrations/2020_02_13_235911_create_question_pools_table.php
> +            $table->timestamps();
It's missing the table fields !!!

2020-02-15 02:57 UTC, LFortunatoC requested changes

2020-02-15 02:57 UTC, LFortunatoC commented on database/migrations/2020_02_13_234350_create_evaluations_table.php
> +            $table->bigIncrements('id');
It's missing the table fields

2020-02-15 21:58 UTC, merged